server:
  port: 8081
spring:
  application:
    name: hello-first
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka
  instance:
    instance-id: provider-hello
    prefer-ip-address: true

#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream
