spring:
  application:
    name: hystrix-dashboard-server
server:
  port: 8870
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: hystrix
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
logging:
  level:
    root: debug
