server:
  port: 8084
spring:
  application:
    name: hello-first
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka
  instance:
    instance-id: provider-hello-copy
    prefer-ip-address: true